name: Access Token Generator

on:
  workflow_call:
    secrets:
      app_id:
        required: true
      private_key:
        required: true

    inputs:
      timeout_minutes:
        required: false
        type: number
        default: 2

    outputs:
      access_token:
        description: "Access token"
        value: ${{ jobs.ci-setup.outputs.access_token }}

jobs:
  auth:
    name: Generate Access Token
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    outputs:
      html-files: ${{ steps.html-files.outputs.files }}
      access_token: ${{ steps.store_token.outputs.access_token }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.private_key }}
      - name: Store token
        id: store_token
        run: |
          ACCESS_TOKEN=${{ steps.generate_token.outputs.token }}
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
