name: Python Code Format

on:
  workflow_call:
    inputs:
      timeout_minutes:
        required: false
        type: number
        default: 3
      ci_repository:
        required: true
        type: string
      ci_repository_branch:
        required: true
        type: string
      ci_repository_path:
        required: true
        type: string
      target_path:
        required: false
        type: string
        default: "."
      report_script:
        required: true
        type: string
      skip_job:
        required: false
        type: boolean
        default: false
    secrets:
      access_token:
        required: true
      slack_bot_token:
        required: true

jobs:
  format-py:
    name: Python Code Format
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Skip job
        if: ${{ inputs.skip_job }}
        run: exit 0
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: "x64"
      - name: Run python formatter
        uses: psf/black@stable
        with:
          options: "--diff --check"
          src: ${{ inputs.target_path }}
          version: "21.7b0"
      - name: Generate report
        if: (failure() || cancelled()) && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: archive/github-actions-slack@v1.0.3
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.slack_bot_token }}
          slack-channel: "#ci-status"
          slack-text: ":red_circle: `${{github.repository}}` - `${{github.job}}` \n
            *run_id:* `${{github.run_id}}` *run_number:* `${{github.run_number}}` \n
            *author:* `${{github.actor}}`"
      - name: Clone CI repository
        if: failure() && inputs.ci_repository
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.ci_repository }}
          ref: ${{ inputs.ci_repository_branch }}
          path: ${{ inputs.ci_repository_path }}
          token: ${{ secrets.access_token }}
      - name: Stop on failure
        if: failure() && inputs.ci_repository
        env:
          LENDINGFRONT_PATH: ${{ github.workspace }}
          PYTHONPATH: ${{ github.workspace }}/
        run: |
          pip install requests
          python ${{ inputs.report_script }} \
            --token=${{ secrets.access_token }} \
            --repository-path=${{ github.repository }} \
            --run-id=${{ github.run_id }}
