name: Slack Notification

on:
  workflow_call:
    inputs:
      timeout_minutes:
        required: false
        type: number
        default: 2
      actor:
        required: true
        type: string
      server_url:
        required: true
        type: string
      run_id:
        required: true
        type: string
      run_number:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      slack_webhook_url:
        required: true

jobs:
  slack-notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Generate report via Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "user": "${{ inputs.actor }}",
              "url": "${{ inputs.server_url }}/${{ inputs.repository }}/actions/runs/${{ inputs.run_id }}",
              "info": "run_id: ${{ inputs.run_id }} - run_number: ${{ inputs.run_number }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
