name: Slack Notification

on:
  workflow_call:
    inputs:
      timeout_minutes:
        required: false
        type: number
        default: 2
      ci_repository:
        required: true
        type: string
jobs:
  slack-notification:
    if: (failure() || cancelled()) && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    name: Slack Notification
    runs-on: ubuntu-20.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Generate report message
        if: (failure() || cancelled()) && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: archive/github-actions-slack@v2.6.0
        id: send-message
        with:
          slack-function: send-message
          slack-channel: "#ci-status"
          slack-text: ":red_circle: `${{github.repository}}` - `${{github.job}}` \n
            *run_id:* `${{github.run_id}}` *run_number:* `${{github.run_number}}` \n
            *author:* `${{github.actor}}`"
      - name: Send Slack reaction to report
        uses: archive/github-actions-slack@v2.6.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-function: send-reaction
          slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
          slack-emoji-name: x
          slack-message-timestamp: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}