name: Status Checker

on:
  workflow_call:
    inputs:
      timeout_minutes:
        required: false
        type: number
        default: 4
      repository:
        required: true
        type: string
      ci_repository:
        required: true
        type: string
      ci_repository_branch:
        required: true
        type: string
      ci_repository_path:
        required: true
        type: string
      status_script:
        required: true
        type: string
    secrets:
      access_token:
        required: true
      slack_bot_token:
        required: true

jobs:
  status-checker:
    name: Status Checker
    runs-on: ubuntu-20.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.repository }}
      - name: Clone CI repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.ci_repository }}
          ref: ${{ inputs.ci_repository_branch }}
          path: ${{ inputs.ci_repository_path }}
          token: ${{ secrets.access_token }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
          architecture: "x64"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pip wheel
          pip install requests
      - name: Run CI status checker
        env:
          LENDINGFRONT_PATH: ${{ github.workspace }}
          PYTHONPATH: ${{ github.workspace }}/
        run: |
          python ${{ inputs.status_script }} \
            --token=${{ secrets.access_token }} \
            --repository-path=${{ github.repository }} \
            --target-workflow="Staging Checks" \
            --ref=staging \
            --day=Thursday
      - name: Generate report message
        if: (failure() || cancelled()) && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: archive/github-actions-slack@v2.6.0
        id: send-message
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-function: send-message
          slack-channel: "#ci-status"
          slack-text: ":large_yellow_circle: `${{github.repository}}` - `${{github.job}}`\n
            :link: URL: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|run_id: ${{github.run_id}} - run_number: ${{github.run_number}}>"
      - name: Send Slack reaction to report
        if: (failure() || cancelled()) && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: archive/github-actions-slack@v2.6.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-function: send-reaction
          slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
          slack-emoji-name: warning
          slack-message-timestamp: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
